spring:
  profiles:
    active:
    - dev
---
server: 
  port: 3306
spring:
  profiles: dev #开发环境
  application:
    name: MICROSERVICE-USER-DEV
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
---
server: 
  port: 3305
spring:
  profiles: test #测试环境
  application:
name: MICROSERVICE-USER-TEST
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true